# 项目数据定义
projects:
  - title: 问卷调查
    description: react + antd + redux 项目，客户端使用 nextjs
    # 必须是 xxx-thumbnail.png 格式
    thumbnail: /images/wenjuan-thumbnail.png
    frontend: https://wenjuan.ygqygq2.com
    backend: https://wenjuan-admin.ygqygq2.com

renew: false
